require("dotenv").config({ path: require("path").join(__dirname, "../../.env") });
const { initDb, getDb } = require("./db");

const places = [
  // ─── PARQUES ──────────────────────────────────────────────────────────────
  {
    name: "Parque Ibirapuera",
    category: "Parques",
    address: "Av. Pedro Álvares Cabral, s/n - Vila Mariana, São Paulo",
    description: "O Parque Ibirapuera é um dos maiores parques urbanos do Brasil e um dos principais pontos turísticos de São Paulo. Com mais de 160 hectares de área verde, o parque oferece opções de lazer, cultura e esporte para todos os públicos.",
    image_url: "https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?w=800&q=80",
    rating: 4.9,
    opening_hours: "05:00 - 24:00",
    price_level: "Gratuito",
    highlight: "Perfeito para caminhadas, piqueniques e atividades ao ar livre.",
    is_open: 1,
    latitude: -23.5874,
    longitude: -46.6576,
    instagram: "parqueibirapuera",
    tags: ["parque", "natureza", "esporte", "família", "gratuito"],
  },
  {
    name: "Parque Villa-Lobos",
    category: "Parques",
    address: "Av. Prof. Fonseca Rodrigues, 2001 - Alto de Pinheiros, São Paulo",
    description: "O Parque Villa-Lobos é um dos maiores parques da cidade, com 720 mil m² de área verde. Conta com pistas de ciclismo, quadras esportivas, anfiteatro ao ar livre e uma vasta área de lazer para toda a família.",
    image_url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    rating: 4.6,
    opening_hours: "Ter-Dom 06:00 - 18:00",
    price_level: "Gratuito",
    highlight: "Ciclismo, esporte e natureza a poucos minutos do centro.",
    is_open: 1,
    latitude: -23.5413,
    longitude: -46.7192,
    tags: ["parque", "ciclismo", "esporte", "natureza", "gratuito"],
  },
  {
    name: "Parque Estadual da Cantareira",
    category: "Parques",
    address: "Estr. Pico do Jaraguá, s/n - Tremembé, São Paulo",
    description: "Uma das maiores reservas florestais urbanas do mundo, com mais de 7.900 hectares de Mata Atlântica. Trilhas ecológicas, cachoeiras e uma biodiversidade impressionante a poucos quilômetros do centro da cidade.",
    image_url: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80",
    rating: 4.7,
    opening_hours: "Ter-Dom 08:00 - 17:00",
    price_level: "R$ 18,00",
    highlight: "Uma das maiores florestas urbanas do mundo.",
    is_open: 1,
    latitude: -23.4076,
    longitude: -46.6418,
    tags: ["natureza", "trilha", "mata atlântica", "ecoturismo", "cachoeira"],
  },
  // ─── MUSEUS ───────────────────────────────────────────────────────────────
  {
    name: "MASP",
    category: "Museus",
    address: "Av. Paulista, 1578 - Bela Vista, São Paulo",
    description: "O Museu de Arte de São Paulo Assis Chateaubriand é considerado um dos mais importantes museus de arte do mundo. Seu acervo conta com mais de 10 mil obras, entre pinturas, esculturas, fotografias e objetos de design.",
    image_url: "https://images.unsplash.com/photo-1566127992631-137a642a90f4?w=800&q=80",
    rating: 4.8,
    opening_hours: "Ter-Dom 10:00 - 18:00",
    price_level: "R$ 60,00",
    highlight: "Um dos maiores acervos de arte da América Latina.",
    is_open: 1,
    latitude: -23.5613,
    longitude: -46.6558,
    instagram: "masp.oficial",
    tags: ["arte", "cultura", "museu", "exposição", "história"],
  },
  {
    name: "Pinacoteca de São Paulo",
    category: "Museus",
    address: "Praça da Luz, 2 - Luz, São Paulo",
    description: "A Pinacoteca do Estado de São Paulo é o museu de artes visuais mais antigo de São Paulo. Seu acervo reúne mais de 10 mil obras de arte brasileira produzidas a partir do século XIX.",
    image_url: "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800&q=80",
    rating: 4.8,
    opening_hours: "Qua-Seg 10:00 - 18:00",
    price_level: "R$ 20,00",
    highlight: "O museu de artes visuais mais antigo de São Paulo.",
    is_open: 0,
    latitude: -23.5342,
    longitude: -46.6337,
    instagram: "pinacotecasp",
    tags: ["arte brasileira", "museu", "história", "cultura", "clássico"],
  },
  {
    name: "Museu do Futebol",
    category: "Museus",
    address: "Praça Charles Miller, s/n - Pacaembu, São Paulo",
    description: "Instalado no Estádio do Pacaembu, o Museu do Futebol é dedicado à história do futebol brasileiro. Com exposições interativas e emocionantes, é um programa obrigatório para os apaixonados pelo esporte.",
    image_url: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80",
    rating: 4.7,
    opening_hours: "Ter-Dom 09:00 - 17:00",
    price_level: "R$ 20,00",
    highlight: "A história e a emoção do futebol brasileiro em um só lugar.",
    is_open: 1,
    latitude: -23.5481,
    longitude: -46.6611,
    instagram: "museudofutebol",
    tags: ["futebol", "esporte", "história", "interativo", "Pacaembu"],
  },
  {
    name: "MAM - Museu de Arte Moderna",
    category: "Museus",
    address: "Parque Ibirapuera, Portão 3 - Vila Mariana, São Paulo",
    description: "O Museu de Arte Moderna de São Paulo é referência na produção artística contemporânea brasileira e internacional. Situado no Parque Ibirapuera, realiza exposições temporárias, performances e eventos culturais ao longo do ano.",
    image_url: "https://images.unsplash.com/photo-1536924940401-56b9e0a4ac47?w=800&q=80",
    rating: 4.6,
    opening_hours: "Ter-Dom 10:00 - 18:00",
    price_level: "R$ 15,00",
    highlight: "Arte contemporânea no coração do Parque Ibirapuera.",
    is_open: 1,
    latitude: -23.5872,
    longitude: -46.6565,
    instagram: "mam.sp",
    tags: ["arte moderna", "contemporâneo", "Ibirapuera", "exposição", "cultura"],
  },
  {
    name: "Museu do Ipiranga",
    category: "Museus",
    address: "Parque da Independência, s/n - Ipiranga, São Paulo",
    description: "Reaberto em 2022 após ampla restauração, o Museu do Ipiranga é um dos mais importantes do Brasil. Localizado no Parque da Independência, guarda acervo histórico sobre a formação do Brasil, com mais de 450 mil itens.",
    image_url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80",
    rating: 4.9,
    opening_hours: "Ter-Dom 09:00 - 17:00",
    price_level: "R$ 20,00",
    highlight: "Totalmente restaurado — o museu mais icônico da história do Brasil.",
    is_open: 1,
    latitude: -23.5858,
    longitude: -46.6102,
    instagram: "museudoipiranga",
    tags: ["história", "Brasil", "independência", "museu", "Ipiranga"],
  },
  // ─── PONTOS TURÍSTICOS ────────────────────────────────────────────────────
  {
    name: "Catedral da Sé",
    category: "Pontos Turísticos",
    address: "Praça da Sé, s/n - Sé, São Paulo",
    description: "A Catedral Metropolitana de São Paulo é um dos maiores templos neogóticos do mundo. Sua construção durou mais de 40 anos e o resultado é uma obra monumental com torres de 92 metros de altura e capacidade para 8 mil pessoas.",
    image_url: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80",
    rating: 4.7,
    opening_hours: "Seg-Sex 08:00 - 19:00",
    price_level: "Gratuito",
    highlight: "Uma das maiores catedrais neogóticas do mundo.",
    is_open: 1,
    latitude: -23.5506,
    longitude: -46.6338,
    tags: ["catedral", "história", "centro", "arquitetura", "religião"],
  },
  {
    name: "Beco do Batman",
    category: "Pontos Turísticos",
    address: "R. Gonçalo Afonso - Vila Madalena, São Paulo",
    description: "O Beco do Batman é um famoso corredor de grafite localizado na Vila Madalena. As paredes são completamente cobertas por obras de arte urbana criadas por artistas locais e internacionais, tornando-o um museu a céu aberto.",
    image_url: "https://images.unsplash.com/photo-1551913902-c92207136625?w=800&q=80",
    rating: 4.6,
    opening_hours: "Aberto 24 horas",
    price_level: "Gratuito",
    highlight: "Um museu a céu aberto de grafite e arte urbana.",
    is_open: 1,
    latitude: -23.5554,
    longitude: -46.6907,
    tags: ["grafite", "arte", "cultura", "Vila Madalena", "gratuito"],
  },
  {
    name: "Bairro da Liberdade",
    category: "Pontos Turísticos",
    address: "Liberdade, São Paulo",
    description: "O Bairro da Liberdade é o maior bairro japonês fora do Japão. Repleto de restaurantes, lojas de produtos asiáticos e cultura oriental, é um destino imperdível para quem quer explorar a diversidade cultural de São Paulo.",
    image_url: "https://images.unsplash.com/photo-1504109586057-7a2ae83d1338?w=800&q=80",
    rating: 4.7,
    opening_hours: "Feiras aos domingos 09:00 - 18:00",
    price_level: "Variado",
    highlight: "O maior bairro japonês fora do Japão.",
    is_open: 1,
    latitude: -23.5586,
    longitude: -46.6332,
    tags: ["japonês", "asiático", "gastronomia", "feirinha", "cultura"],
  },
  {
    name: "Theatro Municipal",
    category: "Pontos Turísticos",
    address: "Praça Ramos de Azevedo, s/n - República, São Paulo",
    description: "O Theatro Municipal de São Paulo é um dos mais importantes teatros do Brasil. Inaugurado em 1911, o edifício é um exemplo magnífico da arquitetura eclética, com influências do Barroco e do Renascimento francês.",
    image_url: "https://images.unsplash.com/photo-1580212206771-85e10b28d0e7?w=800&q=80",
    rating: 4.7,
    opening_hours: "Seg-Sex 12:00 - 18:00 (visitas guiadas)",
    price_level: "R$ 25,00",
    highlight: "Arquitetura histórica deslumbrante no centro de São Paulo.",
    is_open: 1,
    latitude: -23.5451,
    longitude: -46.6388,
    tags: ["teatro", "ópera", "história", "arquitetura", "centro"],
  },
  {
    name: "Avenida Paulista",
    category: "Pontos Turísticos",
    address: "Av. Paulista - Bela Vista, São Paulo",
    description: "A Avenida Paulista é o coração financeiro, cultural e turístico de São Paulo. Com 2,8 km de extensão, concentra museus, centros culturais, restaurantes, bancos e uma vida noturna agitada. Aos domingos é fechada para carros.",
    image_url: "https://images.unsplash.com/photo-1544989164-31f7b76e4f91?w=800&q=80",
    rating: 4.8,
    opening_hours: "Aberto 24 horas",
    price_level: "Gratuito",
    highlight: "O símbolo de São Paulo — fechada para carros aos domingos.",
    is_open: 1,
    latitude: -23.5631,
    longitude: -46.6544,
    tags: ["paulista", "centro financeiro", "cultura", "turismo", "domingo"],
  },
  {
    name: "Estação da Luz",
    category: "Pontos Turísticos",
    address: "Praça da Luz, 1 - Luz, São Paulo",
    description: "A Estação da Luz é um dos mais belos exemplos da arquitetura inglesa do início do século XX no Brasil. Construída em ferro e tijolo, a estação abriga o Museu da Língua Portuguesa e é um importante hub de transporte da cidade.",
    image_url: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80",
    rating: 4.6,
    opening_hours: "Seg-Dom 04:00 - 24:00",
    price_level: "Gratuito",
    highlight: "Arquitetura inglesa do século XX e porta de entrada para o centro histórico.",
    is_open: 1,
    latitude: -23.5340,
    longitude: -46.6345,
    tags: ["estação", "história", "arquitetura", "centro", "transporte"],
  },
  // ─── CENTROS CULTURAIS ────────────────────────────────────────────────────
  {
    name: "Japan House São Paulo",
    category: "Centros Culturais",
    address: "Av. Paulista, 52 - Bela Vista, São Paulo",
    description: "A Japan House é um centro cultural dedicado à promoção da cultura, arte, design e gastronomia japonesa. Com exposições temporárias e permanentes, o espaço oferece uma imersão completa na cultura nipônica.",
    image_url: "https://images.unsplash.com/photo-1542931287-023b922fa89b?w=800&q=80",
    rating: 4.8,
    opening_hours: "Ter-Dom 10:00 - 20:00",
    price_level: "Gratuito",
    highlight: "Uma janela para a cultura e design japonês no coração de SP.",
    is_open: 1,
    latitude: -23.5642,
    longitude: -46.6524,
    instagram: "japanhouse_sp",
    tags: ["japão", "cultura", "design", "exposição", "Paulista"],
  },
  {
    name: "CCBB São Paulo",
    category: "Centros Culturais",
    address: "R. Álvares Penteado, 112 - Centro Histórico, São Paulo",
    description: "O Centro Cultural Banco do Brasil em São Paulo ocupa um belíssimo edifício histórico no centro da cidade. Oferece exposições de arte, cinema, teatro e música, muitas vezes com entrada gratuita.",
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    rating: 4.7,
    opening_hours: "Qua-Seg 09:00 - 21:00",
    price_level: "Gratuito",
    highlight: "Programação cultural diversificada no centro histórico.",
    is_open: 1,
    latitude: -23.5437,
    longitude: -46.6347,
    instagram: "ccbb.sp",
    tags: ["cultura", "exposição", "teatro", "cinema", "centro"],
  },
  {
    name: "Instituto Tomie Ohtake",
    category: "Centros Culturais",
    address: "Av. Brigadeiro Faria Lima, 201 - Pinheiros, São Paulo",
    description: "O Instituto Tomie Ohtake é um dos centros culturais mais importantes de São Paulo, dedicado à arte contemporânea, design e arquitetura. O edifício, projetado por Ruy Ohtake, é uma obra arquitetônica por si só.",
    image_url: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80",
    rating: 4.6,
    opening_hours: "Ter-Dom 11:00 - 20:00",
    price_level: "Gratuito",
    highlight: "Arte contemporânea e arquitetura icônica em Pinheiros.",
    is_open: 1,
    latitude: -23.5646,
    longitude: -46.6891,
    instagram: "institutotomieohtake",
    tags: ["arte", "design", "arquitetura", "contemporâneo", "Pinheiros"],
  },
  // ─── MERCADOS ─────────────────────────────────────────────────────────────
  {
    name: "Mercado Municipal de São Paulo",
    category: "Mercados",
    address: "R. da Cantareira, 306 - Centro Histórico, São Paulo",
    description: "O Mercadão, como é carinhosamente chamado, é um dos principais pontos gastronômicos de São Paulo. Com mais de 300 boxes, oferece produtos frescos, embutidos, queijos, e o famoso sanduíche de mortadela.",
    image_url: "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&q=80",
    rating: 4.7,
    opening_hours: "Seg-Sáb 06:00 - 18:00",
    price_level: "Variado",
    highlight: "Experimente o famoso sanduíche de mortadela!",
    is_open: 1,
    latitude: -23.5415,
    longitude: -46.6296,
    tags: ["gastronomia", "mercado", "centro", "mortadela", "turismo"],
  },
  // ─── BARES ────────────────────────────────────────────────────────────────
  {
    name: "Bar Brahma",
    category: "Bares",
    address: "Av. São João, 677 - República, São Paulo",
    description: "Inaugurado em 1948, o Bar Brahma é um dos bares mais tradicionais e históricos de São Paulo. Frequentado por artistas, intelectuais e políticos ao longo de décadas, o espaço preserva o charme da arquitetura art déco e é ponto de encontro obrigatório no centro.",
    image_url: "https://images.unsplash.com/photo-1514362545857-a982b60b9116?w=800&q=80",
    rating: 4.6,
    opening_hours: "Seg-Sex 11:00 - 23:00",
    price_level: "Variado",
    highlight: "Um dos bares mais históricos e tradicionais de São Paulo, desde 1948.",
    is_open: 1,
    latitude: -23.5421,
    longitude: -46.6396,
    instagram: "barbrahmabr",
    tags: ["bar", "tradição", "chopp", "centro", "histórico", "art déco"],
  },
  {
    name: "Bar Léo",
    category: "Bares",
    address: "R. Aurora, 100 - República, São Paulo",
    description: "O Bar Léo é uma instituição no centro de São Paulo, funcionando desde 1945. Conhecido pelo petisco de linguicinha e pelo ambiente descontraído, é parada obrigatória para quem quer experimentar o sabor autêntico dos botecos paulistanos.",
    image_url: "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800&q=80",
    rating: 4.5,
    opening_hours: "Seg-Sáb 11:30 - 23:00",
    price_level: "Variado",
    highlight: "Boteco clássico e autêntico no coração do centro histórico.",
    is_open: 1,
    latitude: -23.5415,
    longitude: -46.6354,
    tags: ["bar", "boteco", "tradição", "petisco", "centro", "linguicinha"],
  },
  {
    name: "Astor Bar",
    category: "Bares",
    address: "R. Delfina, 163 - Vila Madalena, São Paulo",
    description: "O Astor é um dos bares mais badalados de São Paulo, referência em coquetelaria e gastronomia de boteco. Com ambiente sofisticado e descontraído, fica na Vila Madalena e atrai um público diverso em busca de drinks autorais e boa comida.",
    image_url: "https://images.unsplash.com/photo-1527761939622-a14b6f6e1f65?w=800&q=80",
    rating: 4.7,
    opening_hours: "Ter-Dom 18:00 - 02:00",
    price_level: "Variado",
    highlight: "Coquetelaria autoral e o melhor ambiente da Vila Madalena.",
    is_open: 1,
    latitude: -23.5543,
    longitude: -46.6892,
    instagram: "astorbar",
    tags: ["bar", "coquetelaria", "Vila Madalena", "drinks", "descolado"],
  },
  {
    name: "Empório Alto de Pinheiros",
    category: "Bares",
    address: "R. Deputado Lacerda Franco, 300 - Alto de Pinheiros, São Paulo",
    description: "O Empório Alto de Pinheiros é um dos pioneiros da cena de cervejas artesanais em São Paulo. Com mais de 100 rótulos nacionais e importados, o espaço tem ambiente agradável, petiscos deliciosos e uma clientela fiel de apreciadores de boa cerveja.",
    image_url: "https://images.unsplash.com/photo-1558618047-3d34b1b0e6a4?w=800&q=80",
    rating: 4.7,
    opening_hours: "Ter-Dom 17:00 - 00:00",
    price_level: "Variado",
    highlight: "Referência em cervejas artesanais com mais de 100 rótulos.",
    is_open: 1,
    latitude: -23.5463,
    longitude: -46.7029,
    instagram: "emporioaltodepinheiros",
    tags: ["cerveja artesanal", "craft beer", "Pinheiros", "petisco", "bar"],
  },
  {
    name: "Pirajá Bar",
    category: "Bares",
    address: "Av. Brigadeiro Faria Lima, 64 - Pinheiros, São Paulo",
    description: "O Pirajá é um boteco clássico e muito querido da cena paulistana. Famoso pelas almôndegas ao molho shoyu, pelo chopp gelado e pelo ambiente animado, é frequentado por um público fiel de moradores de Pinheiros e Vila Madalena.",
    image_url: "https://images.unsplash.com/photo-1519659528534-7fd733a832a0?w=800&q=80",
    rating: 4.6,
    opening_hours: "Seg-Dom 12:00 - 00:00",
    price_level: "Variado",
    highlight: "O boteco mais querido de Pinheiros — almôndegas lendárias.",
    is_open: 1,
    latitude: -23.5665,
    longitude: -46.6960,
    instagram: "piraja_bar",
    tags: ["boteco", "bar", "Pinheiros", "almôndega", "chopp"],
  },
  {
    name: "Guilhotina Bar",
    category: "Bares",
    address: "R. Cristiano Viana, 572 - Pinheiros, São Paulo",
    description: "O Guilhotina é referência em coquetelaria contemporânea em São Paulo. O bar tem menu criativo com drinks sazonais, ambiente intimista e uma equipe de bartenders premiados. Ótima pedida para quem busca uma experiência sofisticada.",
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&q=80",
    rating: 4.8,
    opening_hours: "Ter-Sáb 18:00 - 02:00",
    price_level: "Variado",
    highlight: "Um dos melhores bares de coquetelaria do Brasil.",
    is_open: 1,
    latitude: -23.5608,
    longitude: -46.6853,
    instagram: "guilhotinabar",
    tags: ["coquetelaria", "cocktail", "Pinheiros", "sofisticado", "drinks"],
  },
  {
    name: "Frangó",
    category: "Bares",
    address: "R. Frei Caneca, 996 - Consolação, São Paulo",
    description: "O Frangó é um bar e restaurante que se tornou um clássico da Vila Pompeia, e agora também presente na Consolação. Famoso pelo frango assado de qualidade, pelo ambiente descontraído e pelos preços honestos.",
    image_url: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&q=80",
    rating: 4.5,
    opening_hours: "Seg-Dom 11:30 - 00:00",
    price_level: "Variado",
    highlight: "Frango assado icônico e ambiente animado para todas as horas.",
    is_open: 1,
    latitude: -23.5489,
    longitude: -46.6567,
    tags: ["bar", "frango", "Consolação", "descontraído", "clássico"],
  },
  {
    name: "Bar do Juarez",
    category: "Bares",
    address: "R. Padre João Manuel, 1164 - Jardim Paulista, São Paulo",
    description: "O Bar do Juarez é um dos botecos mais tradicionais e queridos de São Paulo. Com mais de 50 anos de história, é famoso pelo espetinho de carne, pelo ambiente acolhedor e pelos preços acessíveis. Um clássico que atravessa gerações.",
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    rating: 4.6,
    opening_hours: "Seg-Dom 11:00 - 00:00",
    price_level: "Variado",
    highlight: "Mais de 50 anos servindo os melhores espetinhos de SP.",
    is_open: 1,
    latitude: -23.5672,
    longitude: -46.6619,
    tags: ["boteco", "espetinho", "tradição", "Jardins", "clássico"],
  },
  {
    name: "Riviera Bar",
    category: "Bares",
    address: "Av. Consolação, 2978 - Consolação, São Paulo",
    description: "O Riviera Bar é um ponto cultural histórico de São Paulo, frequentado por artistas, músicos e boêmios desde os anos 1950. Com shows ao vivo regulares e uma atmosfera única, o bar é um símbolo da contracultura paulistana.",
    image_url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    rating: 4.5,
    opening_hours: "Seg-Dom 18:00 - 03:00",
    price_level: "Variado",
    highlight: "Bar histórico com shows ao vivo e espírito boêmio.",
    is_open: 1,
    latitude: -23.5504,
    longitude: -46.6597,
    tags: ["bar", "show ao vivo", "música", "boêmio", "Consolação"],
  },
  {
    name: "SubAstor",
    category: "Bares",
    address: "R. Delfina, 163 - Vila Madalena, São Paulo",
    description: "O SubAstor é o bar subterrâneo do Astor, especializado em uísques e drinques clássicos. Com ambiente intimista, paredes de tijolos e uma carta impressionante de destilados, é o lugar perfeito para uma noite mais sofisticada.",
    image_url: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80",
    rating: 4.8,
    opening_hours: "Ter-Sáb 20:00 - 03:00",
    price_level: "Variado",
    highlight: "Bar subterrâneo intimista — referência em uísques e drinques clássicos.",
    is_open: 1,
    latitude: -23.5544,
    longitude: -46.6893,
    instagram: "subastor",
    tags: ["whisky", "uísque", "cocktail bar", "Vila Madalena", "sofisticado"],
  },
  // ─── BALADAS ──────────────────────────────────────────────────────────────
  {
    name: "D-Edge",
    category: "Baladas",
    address: "Av. Olavo Fontoura, 1209 - Barra Funda, São Paulo",
    description: "A D-Edge é considerada uma das melhores casas noturnas do mundo, figurando em rankings internacionais há anos. Com sistema de som de última geração, lineup de DJs renomados e ambiente futurista, é referência na cena eletrônica global.",
    image_url: "https://images.unsplash.com/photo-1571266752153-9e8a83b77c05?w=800&q=80",
    rating: 4.8,
    opening_hours: "Sex-Sáb 23:00 - 10:00",
    price_level: "Variado",
    highlight: "Uma das melhores casas noturnas do mundo — eletrônica de alto nível.",
    is_open: 0,
    latitude: -23.5267,
    longitude: -46.6630,
    instagram: "dedge",
    tags: ["balada", "eletrônica", "DJ", "Barra Funda", "noite"],
  },
  {
    name: "Cine Joia",
    category: "Baladas",
    address: "Praça Carlos Gomes, 82 - Liberdade, São Paulo",
    description: "Localizado no histórico Cine Joia, na Praça Carlos Gomes, este espaço cultural e noturno une história e modernidade. Com shows, festas e eventos culturais, tem estrutura para 1.500 pessoas e programação variada durante a semana.",
    image_url: "https://images.unsplash.com/photo-1598899134739-37c6abe2beed?w=800&q=80",
    rating: 4.6,
    opening_hours: "Qui-Sáb 22:00 - 06:00",
    price_level: "Variado",
    highlight: "Espaço histórico que mistura cultura, shows e balada.",
    is_open: 0,
    latitude: -23.5598,
    longitude: -46.6330,
    instagram: "cinejoia",
    tags: ["balada", "show", "Liberdade", "cultural", "noite"],
  },
  {
    name: "Clash Club",
    category: "Baladas",
    address: "R. Bento Freitas, 306 - República, São Paulo",
    description: "O Clash Club é um dos clubs mais tradicionais da noite paulistana, com forte identidade LGBTQIA+. Com três pistas e programação eclética que vai do pop ao eletrônico, é referência de diversidade e festa em São Paulo.",
    image_url: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80",
    rating: 4.7,
    opening_hours: "Sex-Sáb 23:00 - 07:00",
    price_level: "Variado",
    highlight: "Referência LGBTQIA+ com três pistas e programação eclética.",
    is_open: 0,
    latitude: -23.5504,
    longitude: -46.6570,
    instagram: "clashclubsp",
    tags: ["balada", "LGBTQIA+", "clube", "dança", "noite"],
  },
  {
    name: "The Week São Paulo",
    category: "Baladas",
    address: "R. Guaicurus, 324 - Lapa, São Paulo",
    description: "The Week é uma das maiores e mais famosas casas noturnas LGBTQIA+ da América Latina. Com capacidade para milhares de pessoas, realiza mega festas com DJs internacionais, performances artísticas e uma energia única.",
    image_url: "https://images.unsplash.com/photo-1578736641330-3155e606cd40?w=800&q=80",
    rating: 4.6,
    opening_hours: "Sex-Sáb 23:00 - 12:00",
    price_level: "Variado",
    highlight: "Uma das maiores casas LGBTQIA+ da América Latina.",
    is_open: 0,
    latitude: -23.5290,
    longitude: -46.7000,
    instagram: "theweeksp",
    tags: ["balada", "LGBTQIA+", "dança", "megaclub", "internacional"],
  },
  {
    name: "Estúdio SP",
    category: "Baladas",
    address: "R. Augusta, 591 - Consolação, São Paulo",
    description: "O Estúdio SP é um dos espaços mais versáteis da noite paulistana, com programação que vai do indie ao eletrônico, passando por shows de rock e hip-hop. Localizado na Rua Augusta, está no coração da cena noturna da cidade.",
    image_url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    rating: 4.5,
    opening_hours: "Qui-Sáb 22:00 - 05:00",
    price_level: "Variado",
    highlight: "Palco para grandes shows e festas na lendária Rua Augusta.",
    is_open: 0,
    latitude: -23.5504,
    longitude: -46.6554,
    tags: ["show", "balada", "rock", "Augusta", "indie"],
  },
  {
    name: "Casa Comigo",
    category: "Baladas",
    address: "R. Aspicuelta, 258 - Vila Madalena, São Paulo",
    description: "A Casa Comigo é um espaço intimista e charmoso na Vila Madalena, que mistura bar, restaurante e pista de dança. Com DJs residentes e programação de música eletrônica e pop, é ótima pedida para quem quer dançar num ambiente aconchegante.",
    image_url: "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80",
    rating: 4.5,
    opening_hours: "Qui-Sáb 20:00 - 03:00",
    price_level: "Variado",
    highlight: "Bar, restaurante e pista num só espaço intimista.",
    is_open: 0,
    latitude: -23.5543,
    longitude: -46.6926,
    instagram: "casacomigo_sp",
    tags: ["balada", "bar", "Vila Madalena", "DJ", "dança"],
  },
  {
    name: "Inferno Club",
    category: "Baladas",
    address: "R. General Jardim, 567 - Vila Buarque, São Paulo",
    description: "O Inferno Club é uma das casas noturnas mais tradicionais do rock underground paulistano. Com shows de bandas nacionais e internacionais de rock, metal e punk, o espaço é referência para quem curte o estilo mais pesado.",
    image_url: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    rating: 4.4,
    opening_hours: "Sex-Sáb 22:00 - 05:00",
    price_level: "Variado",
    highlight: "Templo do rock underground em São Paulo.",
    is_open: 0,
    latitude: -23.5429,
    longitude: -46.6488,
    tags: ["rock", "metal", "show", "underground", "balada"],
  },
  // ─── RESTAURANTES ─────────────────────────────────────────────────────────
  {
    name: "Terraço Itália",
    category: "Restaurantes",
    address: "Av. Ipiranga, 344 - República, São Paulo",
    description: "Localizado no 41º andar do Edifício Itália, o Terraço Itália oferece uma das vistas mais deslumbrantes de São Paulo. Com culinária italiana sofisticada e atendimento impecável, é uma experiência gastronômica única na cidade.",
    image_url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    rating: 4.7,
    opening_hours: "Seg-Dom 12:00 - 15:00",
    price_level: "R$ 200,00+",
    highlight: "Vista panorâmica de SP a 165 metros de altura.",
    is_open: 1,
    latitude: -23.5444,
    longitude: -46.6423,
    instagram: "terracoitalia",
    tags: ["italiano", "fine dining", "vista", "sofisticado", "centro"],
  },
  {
    name: "Famiglia Mancini",
    category: "Restaurantes",
    address: "R. Avanhandava, 81 - Bela Vista, São Paulo",
    description: "A Famiglia Mancini é um dos restaurantes italianos mais tradicionais de São Paulo, funcionando desde 1969. Famosa pelo farto bufê de antepastos, pelas massas artesanais e pelo ambiente familiar e acolhedor que faz os clientes retornarem por décadas.",
    image_url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    rating: 4.7,
    opening_hours: "Seg-Dom 12:00 - 00:00",
    price_level: "Variado",
    highlight: "Desde 1969 — o mais tradicional italiano de São Paulo.",
    is_open: 1,
    latitude: -23.5561,
    longitude: -46.6404,
    instagram: "famigliamancini",
    tags: ["italiano", "massa", "tradicional", "família", "Bela Vista"],
  },
  {
    name: "Mocotó",
    category: "Restaurantes",
    address: "Av. Nossa Senhora do Loreto, 1100 - Vila Medeiros, São Paulo",
    description: "O Mocotó é um dos restaurantes mais premiados e queridos de São Paulo. Com culinária nordestina autêntica e criativa, o restaurante do chef Rodrigo Oliveira conquistou prêmios nacionais e internacionais. O ambiente é descontraído e o cardápio, delicioso.",
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    rating: 4.9,
    opening_hours: "Ter-Sex 12:00 - 22:00",
    price_level: "Variado",
    highlight: "Culinária nordestina premiada pelo chef Rodrigo Oliveira.",
    is_open: 1,
    latitude: -23.4921,
    longitude: -46.6272,
    instagram: "restaurantemocoto",
    tags: ["nordestino", "premiado", "brasileiro", "caldo", "Rodrigo Oliveira"],
  },
  {
    name: "Maní",
    category: "Restaurantes",
    address: "R. Joaquim Antelo, 210 - Jardim Paulistano, São Paulo",
    description: "O Maní da chef Helena Rizzo é um dos melhores restaurantes do Brasil e da América Latina. Com menu degustação criativo que celebra ingredientes brasileiros em preparações contemporâneas, o restaurante já figurou nas listas dos melhores do mundo.",
    image_url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    rating: 4.9,
    opening_hours: "Ter-Sáb 19:30 - 23:00",
    price_level: "R$ 400,00+",
    highlight: "Um dos melhores restaurantes do Brasil — menu degustação incrível.",
    is_open: 1,
    latitude: -23.5638,
    longitude: -46.6660,
    instagram: "mani_restaurante",
    tags: ["fine dining", "brasileiro", "premiado", "Helena Rizzo", "Jardins"],
  },
  {
    name: "Bráz Pizzaria",
    category: "Restaurantes",
    address: "R. Graúna, 125 - Moema, São Paulo",
    description: "A Bráz Pizzaria é uma das pizzarias mais amadas de São Paulo, com diversas unidades pela cidade. Conhecida pela massa fina e crocante, ingredientes de qualidade e ambiente animado, é considerada uma das melhores pizzas da cidade.",
    image_url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
    rating: 4.7,
    opening_hours: "Seg-Dom 18:30 - 23:30",
    price_level: "Variado",
    highlight: "Uma das pizzarias mais queridas e premiadas de São Paulo.",
    is_open: 1,
    latitude: -23.5987,
    longitude: -46.6638,
    instagram: "brazpizzaria",
    tags: ["pizza", "italiano", "tradicional", "Moema", "massa fina"],
  },
  {
    name: "Tordesilhas",
    category: "Restaurantes",
    address: "Al. Tietê, 489 - Jardim Paulista, São Paulo",
    description: "O Tordesilhas da chef Mara Salles é referência em culinária brasileira contemporânea há mais de 25 anos. O cardápio celebra ingredientes e técnicas do Brasil com criatividade e respeito às raízes, tornando-o uma visita obrigatória para amantes da cozinha nacional.",
    image_url: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
    rating: 4.8,
    opening_hours: "Ter-Sex 12:00 - 15:00",
    price_level: "Variado",
    highlight: "Culinária brasileira contemporânea da chef Mara Salles.",
    is_open: 1,
    latitude: -23.5601,
    longitude: -46.6697,
    instagram: "tordesilhas",
    tags: ["brasileiro", "contemporâneo", "Mara Salles", "Jardins", "premiado"],
  },
  {
    name: "Speranza",
    category: "Restaurantes",
    address: "R. Sete de Abril, 199 - Bela Vista, São Paulo",
    description: "A Speranza é um dos restaurantes italianos mais clássicos de São Paulo, com décadas de história. Famosa pelas pizzas à lenha e pelas massas caseiras, o ambiente acolhedor e o serviço atencioso fazem desta casa uma das mais queridas da cidade.",
    image_url: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80",
    rating: 4.6,
    opening_hours: "Ter-Dom 12:00 - 23:00",
    price_level: "Variado",
    highlight: "Pizza à lenha e massas caseiras num clássico italiano de SP.",
    is_open: 1,
    latitude: -23.5505,
    longitude: -46.6412,
    tags: ["pizza", "italiano", "lenha", "tradição", "Bela Vista"],
  },
  {
    name: "Figueira Rubaiyat",
    category: "Restaurantes",
    address: "R. Haddock Lobo, 1738 - Jardim Paulista, São Paulo",
    description: "O Figueira Rubaiyat é um dos restaurantes mais emblemáticos de São Paulo. Instalado sob uma figueira centenária de 12 metros de altura, oferece carnes de altíssima qualidade com estilo contemporâneo e atmosfera única.",
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    rating: 4.8,
    opening_hours: "Seg-Dom 12:00 - 23:30",
    price_level: "R$ 250,00+",
    highlight: "Carnes premiadas sob uma figueira centenária de 12 metros.",
    is_open: 1,
    latitude: -23.5673,
    longitude: -46.6644,
    instagram: "rubaiyatbrasil",
    tags: ["churrasco", "carne", "fine dining", "Jardins", "figueira"],
  },
  {
    name: "Consulado da Bahia",
    category: "Restaurantes",
    address: "R. Estados Unidos, 1645 - Jardim América, São Paulo",
    description: "O Consulado da Bahia traz a autêntica culinária baiana para São Paulo. Moquecas, vatapá, acarajé e outros pratos típicos são preparados com ingredientes importados da Bahia, garantindo sabor e autenticidade incomparáveis.",
    image_url: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=800&q=80",
    rating: 4.6,
    opening_hours: "Ter-Dom 12:00 - 22:00",
    price_level: "Variado",
    highlight: "Moqueca e acarajé autênticos — a Bahia dentro de SP.",
    is_open: 1,
    latitude: -23.5700,
    longitude: -46.6600,
    tags: ["baiano", "moqueca", "nordestino", "acarajé", "tradição"],
  },
  {
    name: "Spot",
    category: "Restaurantes",
    address: "Al. Ministro Rocha Azevedo, 72 - Jardim Paulista, São Paulo",
    description: "O Spot é um restaurante contemporâneo nos Jardins que mistura influências brasileiras, mediterrâneas e asiáticas. Com ambiente descolado, cozinha aberta e cardápio variado, é frequentado por artistas, jornalistas e amantes de boa gastronomia.",
    image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    rating: 4.5,
    opening_hours: "Seg-Sex 12:00 - 23:00",
    price_level: "Variado",
    highlight: "Gastronomia contemporânea com influências do mundo nos Jardins.",
    is_open: 1,
    latitude: -23.5684,
    longitude: -46.6558,
    tags: ["contemporâneo", "Jardins", "cozinha aberta", "moderno", "descolado"],
  },
];

function seed() {
  const db = initDb();

  const existingCount = db.prepare("SELECT COUNT(*) as count FROM places").get();
  if (existingCount.count > 0) {
    console.log(`Banco já possui ${existingCount.count} lugares. Seed ignorado.`);
    console.log("Para recriar, delete o arquivo lazersp.db e rode novamente.");
    return;
  }

  const insertPlace = db.prepare(`
    INSERT INTO places (name, category, address, description, image_url, rating, opening_hours, price_level, highlight, is_open, latitude, longitude, instagram)
    VALUES (@name, @category, @address, @description, @image_url, @rating, @opening_hours, @price_level, @highlight, @is_open, @latitude, @longitude, @instagram)
  `);

  const insertTag = db.prepare(`
    INSERT INTO tags (place_id, name) VALUES (?, ?)
  `);

  const seedAll = db.transaction(() => {
    for (const place of places) {
      const { tags, ...placeData } = place;
      if (!("instagram" in placeData)) placeData.instagram = null;
      const result = insertPlace.run(placeData);
      const placeId = result.lastInsertRowid;
      for (const tag of tags) {
        insertTag.run(placeId, tag);
      }
    }
  });

  seedAll();
  console.log(`✅ Seed concluído! ${places.length} lugares inseridos.`);
}

seed();
